### PR TITLE
Catkinized and using Wit.ai API

### PR DESCRIPTION
**Pull request by danielchalef**
I've catkinized the package. It now installs cleanly on Indigo and Jade using `catkin_make`.

I've moved to using the Wit.ai API. 

The Outcome message format is significantly different to the existing one. TBH, I couldn't work out how the original functioned. I've hopefully modeled the new message for more complex expressions.

Your input appreciated!

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
Wow, looks good on first impression. I just got back from vacation, I'll take a good look and probably merge later.

**Comment by danielchalef** [comment]
Great. Let me know if you'd like me to make any changes to the PR.

**Comment by LoyVanBeek** [comment]
Works like a charm (as expected). 

Installing pywit itself took a lot of time, apparently I needed to do a 
```bash 
sudo apt-get install curl
sudo apt-get install libsox-dev
sudo pip install wit
```

**Comment by danielchalef** [comment]
Great. Yes, that should perhaps be documented.






On Tue, Sep 22, 2015 at 9:00 AM -0700, "Loy" <notifications@github.com> wrote:












Works like a charm (as expected). 



Installing pywit itself took a lot of time, apparently I needed to do a 

sudo apt-get install curl
sudo apt-get install libsox-dev
sudo pip install wit

**Pull request merged**
